### ISSUE TITLE
Publish  the power meter faces?

### ISSUE THREAD

**Issue by whiskeyriver** [gradyh/Photon-Weather-Station#1]
Could you publish the power meter faces you made as well?

**Comment by gradyh** [comment]
Ryan,

I didn't realize I could post a DWG. I'll put it up today after work.

On Tue, Dec 1, 2015 at 4:01 AM, Ryan Parr notifications@github.com wrote:

> Could you publish the power meter faces you made as well?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gradyh/Photon-Weather-Station/issues/1.

## 

Grady Hillhouse

**Comment by gradyh** [comment]
POSTED
