### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by dstriegel** [gradyh/Photon-Weather-Station#2]
Any chance you could share a simple wiring diagram?  I tried to piece it together from the front and back frames in the video but can't quite see how you have the potentiometers wired in serial on the back side.  Is the power provided through the WKP?  New to particle photon.  Thanks in advance.

**Comment by gradyh** [comment]
![wiring_diagram](https://cloud.githubusercontent.com/assets/11914694/11531489/cb7dd742-98c2-11e5-8517-1fbe557323ad.PNG)

Everything is powered by the signal pins on the photon. Hope this helps!
